train:
  audio: # name of the tensor on which we apply transform
    _target_: torchvision.transforms.v2.Compose
    transforms:
      - _target_: torch_audiomentations.PitchShift
        sample_rate: 16000
      - _target_: torch_audiomentations.AddColoredNoise
        sample_rate: 16000
