train:
  audio: # name of the tensor on which we apply transform
    _target_: torchvision.transforms.v2.Compose
    transforms:
      - _target_: src.transforms.wav_augs.PitchShift
        sample_rate: 16000
      - _target_: src.transforms.wav_augs.AddColoredNoise
        sample_rate: 16000
